### ISSUE TITLE
Huge overestimation of the Q values and lack of convergence

### ISSUE THREAD

**Issue by rayset** [sfujim/TD3#24]
So I'm working with this environment

https://gist.github.com/iandanforth/e3ffb67cf3623153e968f2afdfb01dc8

which is basically the mujoco cart pole.

What I notice is that the value function estimates provided by the target critics steadily increase as training goes on, going way beyond the maximum cumulative reward (even without accounting for the discount). 
The environment is solved after quite few iterations when the estimates are MUCH lower than the real Q values, but continuing the iterations makes the critic diverge several orders of magnitude.

I tried reducing tau and increasing policy_freq, but this unstable behaviour still emerges. 
Did you observe something similar with the mujoco?

**Comment by sfujim** [comment]
Solving before the estimates match the real Q value is likely just because the value hasn't been propagated fully, i.e. the critic is just estimating the value of trajectories of length X < horizon. For many problems, a high performance can be achieved by only considering a short horizon.

The overestimation/divergence might be explained by some of my other [work](https://arxiv.org/abs/1812.02900). If you continue to train past success, the buffer fills with a lot of redundant data. As a result, the critic begins to extrapolate the less frequently seen state-action pairs, and unrealistic values are propagated into the system.
