### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by ikostrikov** [sfujim/TD3#4]
What code did you use to get the plots for the paper?

When I plot the numbers from npy files I'm getting slightly less smooth curves.

**Comment by sfujim** [comment]
Since we compared against a lot of methods, and the graphs are small, every curves was smoothed with a [uniform filter](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.filters.uniform_filter1d.html) with size=20 for visual clarity.

I wish it wasn't necessary, but it becomes difficult to interpret the graphs otherwise, especially on environments where some of the other methods are less stable.
