### ISSUE TITLE
Done state is set to 0 if episode timesteps are greater than or equal to max episode timesteps

### ISSUE THREAD

**Issue by nilsblank** [sfujim/TD3#41]
Hello,

First of all, thanks for publishing the code.

I have a question regarding your implementation:
In the main loop
https://github.com/sfujim/TD3/blob/385b33ac7de4767bab17eb02ade4a268d3e4e24f/main.py#L127 
you set the done flag to false if the episode timesteps are greater than or equal to the max episode timesteps.
From my understanding, this results in the done flag always being False for environments without terminal states.
Is this behavior intended? Shouldn't the done flag be True if the max time steps are exceeded?
When examining the performance of ourDDPG with setting the done state to 1 I achieve a much lower reward compared to the reward obtained when setting the state to 0 in the Half-Cheetah Env.

**Comment by sfujim** [comment]
This is indeed the intended behavior. Since the state does not provide any time step information, termination due to max time steps breaks the Markov property. 

In practice, what this means is that termination from max time steps can hurt performance because it penalizes the arbitrary final state. And since the agent has no way of distinguishing whether this termination occurred due to max time steps or some failure condition, it may learn to avoid these states. Instead, we can just treat the environment as an infinite horizon task and avoid this problem entirely. 

Alternatively, we could provide the time step information to the agent, but this requires more effort!

One downside is if the agent terminates due to a proper condition on the final time step, then we would be introducing some bias. This could be solved with more direct access to the environment, but I believe this almost never occurs in practice anyway.

Thanks for asking!
